(function(){var d=document,w=window;var r=[];function add(id,wcag,level,msg,count){r.push({id:id,wcag:wcag,level:level,msg:msg,count:count});}
var html=d.documentElement;if(!(html.getAttribute('lang')||'').trim())add('lang','3.1.1','A','Attribut lang absent sur <html>',1);
var imgs=[].slice.call(d.querySelectorAll('img')).filter(function(i){return !i.hasAttribute('alt')});if(imgs.length)add('img-alt','1.1.1','A','Images sans attribut alt',imgs.length);
var hs=[].slice.call(d.querySelectorAll('h1,h2,h3,h4,h5,h6')).map(function(h){return +h.tagName[1]});if(hs.indexOf(1)<0)add('h1','2.4.6','AA','Aucun <h1>',1);
var skips=0;for(var i=1;i<hs.length;i++)if(hs[i]-hs[i-1]>1)skips++;if(skips)add('h-skip','1.3.1','A','Sauts de niveau de titre',skips);
var empty=[].slice.call(d.querySelectorAll('a,button')).filter(function(e){return !(e.textContent||'').trim()&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')&&!e.getAttribute('title')&&!e.querySelector('img[alt]')});if(empty.length)add('empty-ctrl','2.4.4 / 4.1.2','A','Liens ou boutons sans nom accessible',empty.length);
var ctrls=[].slice.call(d.querySelectorAll('input:not([type=hidden]):not([type=submit]):not([type=button]),select,textarea'));var unl=ctrls.filter(function(c){var id=c.getAttribute('id');return !(id&&d.querySelector('label[for="'+id+'"]'))&&!c.closest('label')&&!c.getAttribute('aria-label')&&!c.getAttribute('aria-labelledby')});if(unl.length)add('label','1.3.1 / 3.3.2','A','Champs de formulaire sans étiquette',unl.length);
var ids={},dup=0;[].slice.call(d.querySelectorAll('[id]')).forEach(function(e){var k=e.getAttribute('id');if(ids[k])dup++;ids[k]=1});if(dup)add('dup-id','4.1.1','A','Identifiants dupliqués',dup);
var small=[].slice.call(d.querySelectorAll('a,button,input,select,textarea,[role=button]')).filter(function(e){var b=e.getBoundingClientRect();return b.width>0&&b.height>0&&(b.width<24||b.height<24)});if(small.length)add('target','2.5.8','AA','Cibles interactives < 24×24 px (exceptions possibles)',small.length);
if(!d.querySelector('a[href^="#"]')&&!d.querySelector('main,[role=main]'))add('bypass','2.4.1','A','Ni lien d\'évitement ni région main',1);
var old=d.getElementById('a11y-express');if(old)old.remove();var p=d.createElement('div');p.id='a11y-express';p.setAttribute('role','dialog');p.setAttribute('aria-label','A11y Express');p.style.cssText='position:fixed;top:12px;right:12px;z-index:2147483647;max-width:420px;max-height:80vh;overflow:auto;background:#fff;color:#111;border:2px solid #0b6e4f;border-radius:8px;padding:12px;font:14px/1.4 system-ui,sans-serif;box-shadow:0 4px 16px rgba(0,0,0,.25)';
var h='<strong>A11y Express</strong> — '+(r.length?r.length+' constat(s)':'aucun constat')+' (vérifications automatiques partielles, pas un audit WCAG complet)<ul style="padding-left:18px">';r.forEach(function(x){h+='<li><b>'+x.msg+'</b> — '+x.count+' — WCAG '+x.wcag+' ('+x.level+')</li>'});h+='</ul><button id="a11yx-copy">Copier le JSON</button> <button id="a11yx-close">Fermer</button>';p.innerHTML=h;d.body.appendChild(p);
d.getElementById('a11yx-close').onclick=function(){p.remove()};d.getElementById('a11yx-copy').onclick=function(){var t=JSON.stringify({url:location.href,date:new Date().toISOString(),findings:r},null,2);if(navigator.clipboard)navigator.clipboard.writeText(t);else prompt('JSON',t)};})();
